esphome:
  name: demo

esp32:
  board: esp32doit-devkit-v1

logger:

wifi:
  ssid: "GirlsDay"
  password: "GirlsDay"
  
http_request:
  timeout: 5s

# interval:
#   - interval: 3sec
#     then:
#       - http_request.get:
#           url: "https://www.girlsday.CHANGEME/counter.php?action=increment"
#           verify_ssl: false

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
    name: "Button"
    on_multi_click:
    - timing:
        - ON for at most 1s
        - OFF for at most 1s
        - ON for at most 1s
        - OFF for at least 0.2s
      then:
        - http_request.get:
            url: "https://www.girlsday.CHANGEME/counter.php?action=decrement"
            verify_ssl: false
    - timing:
        - ON for at least 3s
      then:
        - http_request.get:
            url: "https://www.girlsday.CHANGEME/counter.php?action=reset"
            verify_ssl: false
    - timing:
        - ON for at most 1s
        - OFF for at least 0.5s
      then:
        - http_request.get:
            url: "https://www.girlsday.CHANGEME/counter.php?action=increment"
            verify_ssl: false
